### ISSUE TITLE
Sourcemaps support is missing

### ISSUE THREAD

**Issue by tk-o** [thgh/rollup-plugin-scss#7] opened 2017-03-13 07:26 UTC
I was trying to use sourcemaps for the SCSS files (as [`node-sass`](https://github.com/sass/node-sass#sourcemap) provide them) but it seems that feature has been omitted during development of this plugin.

**Comment by thgh** [comment] 2017-03-13 09:38
Does it work when you pass `sourceMapEmbed` as option to the scss plugin?
https://github.com/sass/node-sass#sourcemapembed

I agree that when sourceMap=true is set in the rollup config, the plugin should create source maps. 
I don't know how source maps works precisely, so will probably not get them to reference the vue file. I hope to take a stab at it soon!

PR welcome!

**Comment by kopacki** [comment] 2017-03-13 10:16
I had a first look on that. `node-sass` render method returns `css` binary and when required `map` binary as well. The problem is that only `css` value is being write to file. I believe I will manage to create the PR this week.

**Comment by rojakcoder** [comment] 2019-01-14 07:31
@thgh `sourceMapEmbed` works but not for having the map as a separate file.

**Comment by thgh** [comment] 2019-01-17 16:51
How about turning the sourceMapEmbed option on and split the output in code/map, would that work?

**Comment by rojakcoder** [comment] 2019-01-18 23:03
When you say "split the output in code/map", do you mean writing code to separate the embedded source map?

If so, I don't think most, if not all, users would want to do that. The README says "Options are passed to node-sass", so users would expect that all the options node-sass accepts would just work.

I'm not sure what the issue is that is preventing this function from working. Is it because of the `outFile` parameter which states "[enabling this option will not write the file on disk for you](https://www.npmjs.com/package/node-sass#outfile)"?

**Comment by slikts** [comment] 2020-02-27 01:36
Is this how the option is supposed to be passed?
```js
scss({
  sourceMapEmbed: true,
})
```

**Comment by moritzebeling** [comment] 2020-12-18 10:59
`sourceMapEmbed: true` works, but is only a fallback solution during development. Unfortunately it easily doubles the css bundle size, so this is no option for production. Would be really great to have the sourcemap in a separate file, just like the sass docs suggest: https://sass-lang.com/documentation/js-api#source-maps
Thank you for considering that!

**Comment by astappiev** [comment] 2021-01-06 17:17
I solved the issue for myself and provided a PR #66. Feel free to test it and improve

**Comment by thgh** [comment] 2021-02-19 11:50
Sourcemap support has been merged!

**Closed by thgh** 2021-02-19 11:50 UTC

**Comment by cwadrupldijjit** [comment] 2021-04-29 23:48
This should be documented.  Only way to know about this right now is by going to this issue and then on to the associated PR.

I'd add it in another PR, but I'm currently busy and can't take too much time to do that.

**Comment by cwadrupldijjit** [comment] 2021-04-30 00:10
Ah, I finally see what's happening here.  It looks like this is in version 3, but that hasn't been released yet.  Looking at the PR, I might temporarily throw those changes into the version I have so that I can have it.  When is v3 going to be released?

**Comment by thgh** [comment] 2021-05-01 14:19
Soon, I hoped to get more feedback, but let's just release it and see what comes of it.
